#!/bin/bash
#
# Author: Jeroen Op 't Eynde
# Github: Duologic
#
# This script can make incremental backups with Rsync.
# - from local to local
# - from local to remote
# - from remote to local
#
# Todo: from remote to remote
#
# Execute as:
#   ./incremental_rsync /path/to/config.cfg
#
# Config file:
#   prefix="my_backup"
#   amount=10
#   source_ssh="false"
#   source="/home"
#   exclude_file="example_excludes.cfg"
#   #source_key=""
#   #source_user=""
#   #source_host=""
#
#   destination_ssh="true"
#   destination="/backup"
#   destination_key="/home/user/.ssh/rsync-key"
#   destination_user="root"
#   destination_host="backup.somedomain.tld"
#
#   from_mail="noreply@somedomain.tld"
#   to_mail="admin@somedomain.tld"
#   smtp_server="smtp.somedomain.tld"
#
# Exclude file: (paths relative to source folder)
#   - excludedir/
#   - exclude_file
#

amount=24 #default amount
source $1

pid=$$
date=`date "+%Y-%m-%d_%H:%M"`
logfile=/var/log/$prefix.$pid.log
tmpfile=/tmp/$prefix.$date.log
pidfile=/tmp/incremental_rsync.pid
rsynccommand="rsync -az -H --stats"
exitcode=0

[[ ! -f $logfile ]]; touch $logfile
[[ ! -f $tmpfile ]]; touch $tmpfile

log()
{
    while read mes
    do
        echo "$(date +"%b %e %k:%M:%S") $(hostname) $(echo $0)[$$]: $mes" 2>> $tmpfile 1>> $tmpfile
    done
}

{

if [[ -f $pidfile ]]; then
    echo "Script already in use, PID file exists."
    exitcode=1
    exit $exitcode
fi

echo $pid > $pidfile

if [[ "$source_ssh" == "false" ]]; then
    source_ssh=false
elif [[ "$source_ssh" == "true" ]]; then
    source_ssh=true
fi
if [[ "$destination_ssh" == "false" ]]; then
    destination_ssh=false
elif [[ "$destination_ssh" == "true" ]]; then
    destination_ssh=true
fi

if [[ -n $bwlimitinkbps ]]; then
    rsynccommand="$rsynccommand --bwlimit=$bwlimitinkbps"
fi

if [[ -n $exclude_file ]]; then
    rsynccommand="$rsynccommand --exclude-from=$exclude_file"
fi

linkdest="$destination/$prefix.1"
backdest="$destination/$prefix.0"

source_sshstring="$source_user@$source_host"
destination_sshstring="$destination_user@$destination_host"

echo "Backup on $date  as $(whoami)"

# Remove oldest backup
max=$amount
to_remove=$destination/$prefix.$max;

if $destination_ssh; then
    ssh -i $destination_key $destination_sshstring "rm -rf $to_remove"
else
    rm -rf $to_remove
fi

counter=$(echo $max-1|bc)
echo "Refactoring directories..."
while [ $counter -gt -1 ]; do
    to_movefrom="$destination/$prefix.$counter"
    to_moveto="$destination/$prefix.$(echo $counter+1|bc)"
    if $destination_ssh; then
        ssh -i $destination_key $destination_sshstring "mv -f $to_movefrom $to_moveto"
    else
        mv -f $to_movefrom $to_moveto
    fi
    counter=$(echo $counter-1|bc)
done

echo "Check if linkdest $linkdest exists on receiving side..."

linkdestexists=1
if $destination_ssh; then
    ssh -i $destination_key $destination_sshstring "test -d $linkdest"
    linkdestexists=$?
else
    if [[ -d $linkdest ]]; then
        linkdestexists=0
    fi
fi

if [[ $linkdestexists==0 ]]; then
    rsynccommand="$rsynccommand --link-dest=$linkdest"
fi

echo "Rsync Backup $source_sshstring:$source to $destination_sshstring:$backdest"

if $source_ssh; then
    rsynccommand="$rsynccommand -e 'ssh -i $source_key ' $source_sshstring:$source $backdest"
elif $destination_ssh; then
    rsynccommand="$rsynccommand -e 'ssh -i $destination_key ' $source $destination_sshstring:$backdest"
else
    rsynccommand="$rsynccommand $source $backdest"
fi

echo "Executing: $rsynccommand"
bash -c "$rsynccommand"

date=`date "+%Y-%m-%d %H:%M"`
echo "Done on $date."

rm -rf $pidfile
#}|logger -i -p local0.notice -t "$(basename $0)" -s 
} 2>&1 | log
#}
sendemail -f $from_mail -t $to_mail -u "[script_output] $prefix" -m "$prefix has been executed." -s $smtp_server -a $tmpfile

if profile; then
    profiler_date = $(date +%s)
    profiler_sent = $(grep -e "sent [0-9]\+" $tmpfile|cut -d']' -f2|cut -d' ' -f3)
    profiler_received = $(grep -e "sent [0-9]\+" $tmpfile|cut -d']' -f2|cut -d' ' -f7)
    profiler_speed = $(grep -e "sent [0-9]\+" $tmpfile|cut -d']' -f2|cut -d' ' -f10)

    echo "$profiler_string.incremental_rsync.sent $profiler_sent $profiler_date" | nc $carbon_server $carbon_port -c
    echo "$profiler_string.incremental_rsync.received $profiler_received $profiler_date" | nc $carbon_server $carbon_port -c
    echo "$profiler_string.incremental_rsync.speed $profiler_speed $profiler_date" | nc $carbon_server $carbon_port -c
fi

cat $tmpfile >> $logfile
rm $tmpfile

exit $exitcode 
